import test from "node:test";
import assert from "node:assert/strict";
// Node's type-stripping test runner requires the explicit extension.
// @ts-expect-error TS5097 is intentional for direct Node execution.
import { defaultPlannerState,generateSchedule,markMissedAndReschedule,type PlannerAssignment } from "../lib/planner.ts";

function assignment(overrides:Partial<PlannerAssignment>={}):PlannerAssignment{return {id:1,termId:"fall-2027",subject:"Biology",title:"Lab report",type:"assignment",due:"2027-09-10T22:00:00.000Z",priority:"High",estimatedMinutes:120,subtasks:[{id:"draft",title:"Draft",estimatedMinutes:120,completed:false,order:0}],practiceQuestions:false,status:"active",...overrides}}

test("schedules only inside availability and daily limit",()=>{const state=defaultPlannerState("America/Chicago");state.preferences.activeTermId="fall-2027";state.preferences.sessionMinutes=45;state.preferences.maxDailyMinutes=90;state.preferences.availability=[{day:1,start:"16:00",end:"18:00"}];state.assignments=[assignment()];const result=generateSchedule(state,new Date("2027-09-06T12:00:00.000Z"));assert.equal(result.sessions.length,2);assert.equal(result.warnings.length,1);const firstDay=result.sessions.filter(item=>item.start.slice(0,10)===result.sessions[0].start.slice(0,10));assert.ok(firstDay.length<=2);for(const session of result.sessions){const hour=new Date(session.start).toLocaleString("en-US",{timeZone:"America/Chicago",hour:"numeric",hour12:false});assert.ok(Number(hour)>=16&&Number(hour)<18)}});

test("respects recurring commitments and one-off exceptions",()=>{const state=defaultPlannerState("America/Chicago");state.preferences.activeTermId="fall-2027";state.preferences.availability=[{day:1,start:"16:00",end:"20:00"}];state.preferences.commitments=[{id:"sport",title:"Practice",day:1,start:"16:00",end:"17:00"}];state.preferences.exceptions=[{id:"appointment",title:"Appointment",start:"2027-09-06T22:00:00.000Z",end:"2027-09-06T23:00:00.000Z",source:"manual"}];state.assignments=[assignment({estimatedMinutes:45,subtasks:[{id:"draft",title:"Draft",estimatedMinutes:45,completed:false,order:0}]})];const result=generateSchedule(state,new Date("2027-09-06T12:00:00.000Z"));assert.equal(result.sessions.length,1);assert.equal(new Date(result.sessions[0].start).toISOString(),"2027-09-06T23:00:00.000Z")});

test("keeps terms isolated",()=>{const state=defaultPlannerState();state.preferences.activeTermId="fall-2027";state.assignments=[assignment(),assignment({id:2,termId:"spring-2028",title:"Other term"})];const result=generateSchedule(state,new Date("2027-09-06T12:00:00.000Z"));assert.ok(result.sessions.every(item=>item.assignmentId===1))});

test("missed sessions produce an undoable revision",()=>{const state=defaultPlannerState();state.sessions=[{id:"late",assignmentId:1,subtaskId:null,title:"Late work",subject:"Math",start:"2020-01-01T10:00:00.000Z",end:"2020-01-01T11:00:00.000Z",status:"planned",location:"",trigger:"",actualMinutes:null,difficulty:null,updatedAt:"2020-01-01T10:00:00.000Z"}];const result=markMissedAndReschedule(state,new Date("2020-01-02T00:00:00.000Z"));assert.equal(result.revisions[0].reason,"Missed work was redistributed");assert.equal(result.revisions[0].undone,false);assert.equal(result.revisions[0].before[0].id,"late")});
