"use client";
import { FormEvent,useEffect,useState } from "react";
import type { AuthSession } from "../supabase";
import Link from "next/link";

type Profile={fullName:string;username:string;email:string;classes:string[]};

export function SettingsPage(){
 const [tab,setTab]=useState<"account"|"classes">("account"),[session,setSession]=useState<AuthSession|null>(null),[profile,setProfile]=useState<Profile|null>(null),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 useEffect(()=>{const wanted=new URLSearchParams(window.location.search).get("tab");const saved=localStorage.getItem("aster-session");if(!saved){window.location.replace("/");return}const next=JSON.parse(saved) as AuthSession;void fetch("/api/profile",{headers:{authorization:`Bearer ${next.access_token}`}}).then(async response=>{if(response.status===401){localStorage.removeItem("aster-session");window.location.replace("/");return}const data=await response.json() as {profile:Profile|null};if(!data.profile){window.location.replace("/");return}setSession(next);setTab(wanted==="classes"?"classes":"account");setProfile(data.profile);setLoading(false)})},[]);
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!profile||!session)return;const form=new FormData(event.currentTarget),next={...profile,fullName:tab==="account"?String(form.get("fullName")):profile.fullName,username:tab==="account"?String(form.get("username")):profile.username,classes:tab==="classes"?String(form.get("classes")).split(",").map(x=>x.trim()).filter(Boolean):profile.classes};if(!next.classes.length){setMessage("Add at least one class.");return}const response=await fetch("/api/profile",{method:"PUT",headers:{"content-type":"application/json",authorization:`Bearer ${session.access_token}`},body:JSON.stringify(next)});if(!response.ok){setMessage((await response.json()).error||"Changes could not be saved.");return}setProfile(next);setMessage(tab==="account"?"Account details saved.":"Classes updated.")}
 function signOut(){localStorage.removeItem("aster-session");window.location.replace("/")}
 if(loading)return <main className="settings-loading"><span>✦</span><p>Opening settings…</p></main>;
 return <main className="settings-shell"><aside className="settings-rail"><Link className="brand" href="/"><span className="brand-mark">A</span><span>Aster</span></Link><Link className="settings-back" href="/">← Back to planner</Link><div><small>SETTINGS</small><button className={tab==="account"?"active":""} onClick={()=>{setTab("account");setMessage("")}}><span>◎</span><div><strong>Account</strong><small>Profile and email</small></div></button><button className={tab==="classes"?"active":""} onClick={()=>{setTab("classes");setMessage("")}}><span>▤</span><div><strong>Classes</strong><small>Your current term</small></div></button></div><button className="settings-signout" onClick={signOut}>Sign out</button></aside><section className="settings-content"><header><small>PERSONAL SETTINGS</small><h1>{tab==="account"?"Account":"Classes"}</h1><p>{tab==="account"?"Manage how you appear in your Aster workspace.":"Keep your class list current so every assignment stays organized."}</p></header>{tab==="account"?<form className="settings-card" onSubmit={save}><div className="settings-card-head"><div className="settings-avatar">{profile?.fullName.split(" ").map(x=>x[0]).slice(0,2).join("")}</div><div><h2>Profile information</h2><p>This information is visible only in your workspace.</p></div></div><label>Full name<input name="fullName" defaultValue={profile?.fullName} required/></label><label>Username<div className="username-input"><span>@</span><input name="username" defaultValue={profile?.username} pattern="[a-zA-Z0-9_-]{3,24}" required/></div><small>3–24 letters, numbers, dashes, or underscores.</small></label><label>Email address<input value={profile?.email} readOnly/><small>Your verified login email cannot be changed here.</small></label>{message&&<p className="settings-message">{message}</p>}<button className="bright-button" type="submit">Save account</button></form>:<form className="settings-card" onSubmit={save}><div className="settings-card-head"><span className="settings-class-icon">▤</span><div><h2>Your class list</h2><p>Assignments can only use classes saved here.</p></div></div><label>Classes<input name="classes" defaultValue={profile?.classes.join(", ")} placeholder="Algebra, Biology, English" required/><small>Separate each class with a comma.</small></label><div className="class-preview">{profile?.classes.map(name=><span key={name}>{name}</span>)}</div>{message&&<p className="settings-message">{message}</p>}<button className="bright-button" type="submit">Save classes</button></form>}</section></main>
}
