import { SUPABASE_PUBLISHABLE_KEY,SUPABASE_URL } from "@/app/supabase";
import { getD1 } from "@/db/runtime";
import { localStore, type LocalAssignment } from "@/app/api/local-store";

async function emailFor(request:Request){const authorization=request.headers.get("authorization");if(!authorization?.startsWith("Bearer "))return null;const response=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SUPABASE_PUBLISHABLE_KEY,authorization}});if(!response.ok)return null;return ((await response.json()) as {email?:string}).email||null}
async function ensure(db:D1Database){await db.batch([db.prepare("CREATE TABLE IF NOT EXISTS assignments (id INTEGER PRIMARY KEY AUTOINCREMENT, user_email TEXT NOT NULL, subject TEXT NOT NULL, title TEXT NOT NULL, due_at TEXT NOT NULL, priority TEXT NOT NULL, hours INTEGER NOT NULL, progress INTEGER NOT NULL DEFAULT 0, reminder_label TEXT NOT NULL DEFAULT 'Never', reminder_at TEXT, reminder_status TEXT NOT NULL DEFAULT 'pending', reminder_attempts INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL DEFAULT (unixepoch()))"),db.prepare("CREATE INDEX IF NOT EXISTS assignments_owner_idx ON assignments(user_email)"),db.prepare("CREATE INDEX IF NOT EXISTS assignments_reminder_idx ON assignments(reminder_status,reminder_at)")])}

export async function GET(request:Request){const email=await emailFor(request);if(!email)return Response.json({error:"Unauthorized"},{status:401});const db=await getD1();if(!db)return Response.json({assignments:localStore.assignments.get(email)??[]});await ensure(db);const result=await db.prepare("SELECT id,subject,title,due_at AS due,priority,hours/100.0 AS hours,progress,reminder_label AS reminderLabel,reminder_at AS reminderAt FROM assignments WHERE user_email=? ORDER BY due_at").bind(email).all();return Response.json({assignments:result.results})}

export async function POST(request:Request){const email=await emailFor(request);if(!email)return Response.json({error:"Unauthorized"},{status:401});const body=await request.json() as {subject?:string;title?:string;due?:string;priority?:string;hours?:number;reminderLabel?:string;reminderAt?:string|null};if(!body.subject||!body.title||!body.due||!body.priority||!body.hours)return Response.json({error:"Missing assignment details."},{status:400});if(body.reminderAt&&new Date(body.reminderAt).getTime()>=new Date(body.due).getTime())return Response.json({error:"Reminder must be before the due time."},{status:400});const db=await getD1();if(!db){const assignment:LocalAssignment={id:localStore.nextAssignmentId++,subject:body.subject,title:body.title,due:body.due,priority:body.priority,hours:body.hours,progress:0,reminderLabel:body.reminderLabel||"Never",reminderAt:body.reminderAt||null};localStore.assignments.set(email,[...(localStore.assignments.get(email)??[]),assignment]);return Response.json({id:assignment.id})}await ensure(db);const result=await db.prepare("INSERT INTO assignments (user_email,subject,title,due_at,priority,hours,reminder_label,reminder_at,reminder_status) VALUES (?,?,?,?,?,?,?,?,?)").bind(email,body.subject,body.title,body.due,body.priority,Math.round(body.hours*100),body.reminderLabel||"Never",body.reminderAt||null,body.reminderAt?"pending":"disabled").run();return Response.json({id:result.meta?.last_row_id??Date.now()})}
